# This configuration file updates the default configuration file
# See https://github.com/searxng/searxng/blob/master/searx/limiter.toml

[botdetection]
# Configure trusted proxies and network settings
trusted_proxies = [
    '127.0.0.0/8',
    '::1',
    '10.0.0.0/8',      # Docker default networks
    '172.16.0.0/12',   # Docker networks  
    '192.168.0.0/16'   # Local networks
]

[botdetection.ip_limit]
# Disable advanced bot protection for local usage
# enable this when running the instance for a public usage on the internet
link_token = false
# Disable link-local filtering to allow Docker networks
filter_link_local = false

[botdetection.ip_lists]
# Pass (whitelist) local and Docker networks
pass_ip = [
    '127.0.0.0/8',      # Localhost
    '10.0.0.0/8',       # Docker default networks
    '172.16.0.0/12',    # Docker networks  
    '192.168.0.0/16',   # Local networks
    '::1',              # IPv6 localhost
    'fe80::/10'         # IPv6 link-local
]

# Allow IPs from SearXNG organization (optional)
pass_searxng_org = true
